export const AUSTRALIAN_SCHOOLS = [
  "Abbotsleigh",
  "Al Noori Muslim School",
  "All Saints' College",
  "Anglican Church Grammar School",
  "Ascham School",
  "Ballarat Grammar School",
  "Barker College",
  "Brisbane Boys' College",
  "Brisbane Grammar School",
  "Brisbane Girls Grammar School",
  "Canberra Grammar School",
  "Caulfield Grammar School",
  "Christ Church Grammar School",
  "Cranbrook School",
  "Geelong Grammar School",
  "Hale School",
  "Iona Presentation College",
  "Knox Grammar School",
  "Melbourne Grammar School",
  "Methodist Ladies' College",
  "Newington College",
  "Pymble Ladies' College",
  "Scotch College",
  "Shore School",
  "St Aloysius' College",
  "St Catherine's School",
  "St Joseph's College",
  "St Peter's College",
  "Sydney Church of England Grammar School (Shore)",
  "Sydney Grammar School",
  "The King's School",
  "Trinity Grammar School",
  "Wesley College",
  "Xavier College"
];

export const SPORT_TYPES: Record<string, string[]> = {
  AFL: [],
  Basketball: [],
  Cricket: [],
  Floorball: [],
  Hockey: [],
  Netball: [],
  Other: [],
  Rugby: [],
  Soccer: [],
};
